### ISSUE TITLE
Publish tsec on npmjs.com

### ISSUE THREAD

**Issue by jrieken** [google/tsec#17]
Related to https://github.com/microsoft/vscode/issues/111289 but I think tsec being on npm with a "real" versioning story would make consumption much simpler

**Comment by koto** [comment]
ACK, we're looking into it. Let us get back to you as soon as we have an update.

**Comment by engelsdamien** [comment]
have you tried pinning `tsec` to a specific commit ? that might help

**Comment by uraj** [comment]
[tsec](https://www.npmjs.com/package/tsec) is now available on npmjs.com. I tried it with VS Code and it should work just fine.

**Comment by jrieken** [comment]
Adopted. Thanks!
