### ISSUE TITLE
Don't run tsc as a post install step

### ISSUE THREAD

**Issue by mjbvz** [google/tsec#20]
**Problem**
I'm trying to bump VS Code's version of TypeScript to the latest nightly. However installing this version into VS Code caused a tsec error (the error happens on `yarn add typescript@next`):

```
> tsec@0.0.1 build /Users/matb/projects/vscode/node_modules/tsec
> tsc

node_modules/@types/node/globals.d.ts(134,5): error TS2687: All declarations of 'url' must have identical modifiers.
node_modules/@types/node/globals.d.ts(134,5): error TS2717: Subsequent property declarations must have the same type.  Property 'url' must be of type 'string | undefined', but here has type 'string'.
../typescript/lib/lib.dom.d.ts(618,5): error TS2687: All declarations of 'url' must have identical modifiers.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! tsec@0.0.1 build: `tsc`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the tsec@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
```

The issue is that `tsec` run `tsc` compile in a post install step:

```
   "build": "tsc",
    "postinstall": "npm run build"
```

The shipped code should likely be precompiled and the post install step removed 

/cc @jrieken

**Comment by uraj** [comment]
For internal reasons, we cannot publish precompiled code at this point. A temporary fix would be adding the tsec dependency as a Git URL instead of a GitHub URL. I will create a PR for this.

We will try to publish precompiled code and put tsec on npmjs.com in this quarter.

**Comment by jrieken** [comment]
> We will try to publish precompiled code and put tsec on npmjs.com in this quarter.

Sorry, I lost patience. I have forked this into https://github.com/jrieken/tsec and that forks sole purpose is to publish tsec on npm as `vscode-tsec`: https://www.npmjs.com/package/vscode-tsec

**Comment by uraj** [comment]
Sorry for the inconvenience. We will solve this problem as soon as possible.

**Comment by jrieken** [comment]
Yeah, no worries. Took the pragmatic way since I don't wanna struggle with yarn-bugs anymore ;-)
