### ISSUE TITLE
Support Trusted Types from DOM lib

### ISSUE THREAD

**Issue by tosmolka** [google/tsec#26]
We are still waiting on DOM lib to fully support Trusted Types (https://github.com/microsoft/TypeScript/issues/30024). I was proposing a fix in https://github.com/microsoft/TypeScript-DOM-lib-generator/pull/1246 but it might take a while to get this merged in and released (= Safari or Firefox start supporting TTs).

I ran tsec against codebase that was using this updated DOM lib and found out that tsec does not recognize these built-in TT types. 

For one, the matcher expects the types to be defined in DefinitelyTyped (@types/trusted-types):

https://github.com/google/tsec/blob/a04e15aa1c3d4086c30ef2ebcfc83325780789dc/src/third_party/tsetse/util/trusted_types_configuration.ts#L27

It would be great if we could add this support to tsec for people (like us) who are already using DOM lib with TTs in their code.

**Comment by uraj** [comment]
Thanks for reporting this. Due to internal issues, tsec can't accept external contributions (as stated in our CONTRIBUTING.md). I will patch this internally and release a new version.

**Comment by uraj** [comment]
Could you provide some details about your setup? Did you swap out the original lib.dom.d.ts and use an updated one? Or is the updated lib.dom.d.ts released as an npm package?

**Comment by tosmolka** [comment]
@uraj , I ended up patching lib.dom.d.ts in my local setup, I pushed patch to https://github.com/google/tsec/pull/27/commits/27256dc26f99c4112323133523bacfe6169dee97 as a reference.

**Comment by tosmolka** [comment]
@uraj , do you have enough info to investigate this further? Thanks.

**Comment by uraj** [comment]
@tosmolka Sorry we're currently working on adding ESLint support. It should be done by the end of this week. After that I will add support for TT in DOM lib.

Another thing that might be useful to know: in which file do you define the Trusted Types? Did you put the definition in lib.dom.d.ts or you have a separate file for Type declaration?

**Comment by uraj** [comment]
@tosmolka I'm about to release a patch. Before that, want to confirm with you on how you amended lib.dom.d.ts. Did you just append something like below to the file?
```typescript
declare class TrustedHTML {}
```

**Comment by tosmolka** [comment]
@uraj , I used this: https://github.com/google/tsec/commit/27256dc26f99c4112323133523bacfe6169dee97 and applied patch using [patch-package](https://www.npmjs.com/package/patch-package).

**Comment by uraj** [comment]
Should be fixed by [1ceed96](https://github.com/google/tsec/commit/1ceed96b9e2a269bfecbfb58f723bbee24ecaf35). Will publish a new version soon.

**Comment by uraj** [comment]
Please try 0.2.4.

**Comment by uraj** [comment]
@tosmolka OK I got what you meant. I will discuss with the team and see whether we should support this form of assignments. With 0.2.4 you can now at least write
```
declare const trustedScriptUrl: string | TrustedScriptURL;
script.src = trustedScriptUrl as string;
```
where `TrustedScriptURL` is defined in the patched lib.dom.d.ts.

**Comment by tosmolka** [comment]
@uraj , do you have any updates regarding support for this form of assignments? Thanks a lot. 

```typescript
declare const trustedScriptUrl: string | TrustedScriptURL;
script.src = trustedScriptUrl;
```

**Comment by uraj** [comment]
@tosmolka With lib.dom.d.ts patched, there is no longer the need to use `string | TrustedScriptURL`. I think we can support the following
```typescript
declare const trustedScriptUrl: TrustedScriptURL;
script.src = trustedScriptUrl;
```
Is that OK to you?

**Comment by uraj** [comment]
We can flag that case, if we detect that `TrustedScriptURL` is defined as an ambient type, i.e., an indicator that lib.dom.d.ts is patched. We should really check if `script.src` actually accepts an `TrustedScriptURL` but that seems a much more complicated change.

**Comment by uraj** [comment]
@tosmolka I've submitted the patch, but for some reason I can't publish a new version right now. I will try over the weekends, but you can try out the patch before that if you want

**Comment by uraj** [comment]
0.2.6 is now published. Please let me know if the new version works for your setup.

**Comment by tosmolka** [comment]
@uraj , I quickly checked the change. 

It seems to be working fine for intersection types - `string & TrustedScriptURL` . But what we need are union types - `string | TrustedScriptURL` - this is still being flagged by tsec as an issue.

**Comment by uraj** [comment]
@tosmolka this is intended. I thought your project is OK with this, per our [previous discussions](#issuecomment-1158850461).

**Comment by tosmolka** [comment]
@uraj , I thought we were discussion union types - `string | TrustedScriptURL` - this is what we are using in our projects, this is what I . I am confused now, are you saying we should change our setup or are you saying you are going to fix this in tsec? Can you add unit tests for these cases into tsec so that the expected behavior is clearer? Thanks.

**Comment by uraj** [comment]
@tosmolka We were indeed talking about union types. The new behavior is that, if tsec found the definition of Trusted Types is ambient, union types like `string|TrustedScriptURL` are not longer acceptable at the sinks, since that *may* cause problems. For consistency, the following case will be flagged as well:

```typescript
declare const trustedScriptUrl: string | TrustedScriptURL;
script.src = trustedScriptUrl as string;
```

On unit tests: we do have them internally, but for some reason we don't export the test code to github.

**Comment by tosmolka** [comment]
@uraj , OK, I misunderstood what is the intended behavior after your fix. Would be good to update docs accordingly at some point. Thanks.
