### ISSUE TITLE
Add option for ignoring TS errors

### ISSUE THREAD

**Issue by tosmolka** [google/tsec#28]
tsec is a wrapper around tsc and reports errors from both custom rules related to Trusted Types as well as standard TypeScript errors (e.g. strict checks). This is expected behavior in most cases as TypeScript errors might prevent tsec from doing it's job. 

We have problem with this approach in complex CI/CD pipelines where we already have jobs that handle standard TypeScript errors. We would like to keep tsec job focused solely on issues related to Trusted Types - fail only on custom checks and ignore others as they are handled (and reported) elsewhere. 

It would be great if we could add a switch/option into tsec that would be false by default and only enable this behavior when needed.

**Comment by uraj** [comment]
I will create a patch for this.

On a related note, would it be helpful in your case if we release an eslint-based tsec? Does that ease your CI/CD integration?

**Comment by tosmolka** [comment]
@uraj , if we could integrate it with https://github.com/microsoft/eslint-plugin-sdl/ that would be a big help. But we use eslint also on plain JS as well as TS without --project and thus without full type checking. We should be prepared to handle those scenarios.

**Comment by lzomlot** [comment]
Any progress on this issue?

**Comment by uraj** [comment]
I have a patch already and is going through internal code review.

**Comment by uraj** [comment]
Please try 0.2.8.
