### ISSUE TITLE
[ban-worker-calls] Is there any best practice for such error ?

### ISSUE THREAD

**Issue by Leteno** [google/tsec#32]
Hello, I am using tsec to guard my typescript project. And it is blocked: 
![image](https://user-images.githubusercontent.com/25839908/178086855-84a152ce-f930-43a9-b431-a031e7e7417f.png)
![image](https://user-images.githubusercontent.com/25839908/178086861-e5ae47ce-3e17-4828-b116-ee0d449c28ee.png) 

So I tried some ways to make it right, like safevalue, it doesn’t work.
![image](https://user-images.githubusercontent.com/25839908/178086863-00debdc4-e366-4a1a-a94a-d0d3efbd7d9d.png)
![image](https://user-images.githubusercontent.com/25839908/178086865-580ba463-0c03-4d30-b924-ce4088af50b3.png)

 
You could also visit my demo https://github.com/Leteno/SecurityDemo/blob/master/app/worker.ts 
I would like to know whether we have best practice for each error. It may be frustrating if people stuck at these issues and have to close tsec.

**Comment by uraj** [comment]
Could you use the safe setters from safevalues? In your case, you can use this function: https://github.com/google/safevalues/blob/568fd090931acb25090fbb40b4e91e54474c02aa/src/dom/globals/worker.ts#L30

**Comment by Leteno** [comment]
Thanks, it works. And I shall close this issue.
